Repository xiangqi-master/xiangqi-master-frontend, pull requests merged in 2025-04, with the labels that each got.

#32 24-refactor-piece-codes-add-color-property
  .eslintrc
  .github/workflows/linter.yml
  src/logic/Color.ts
  src/logic/Piece.ts
  src/logic/factory/PieceCode.ts
  src/logic/factory/PieceFactory.ts
  src/logic/factory/PieceType.ts
  src/logic/factory/index.ts
  src/logic/factory/pieceFactory/AdvisorFactory.ts
  src/logic/factory/pieceFactory/PawnFactory.ts
  src/logic/factory/pieceFactory/RookFactory.ts
  src/logic/pieces/Advisor.ts
  src/logic/pieces/Pawn.ts
  src/logic/pieces/Rook.ts
  src/logic/ui/Ui.ts
  src/logic/utils/Optional.ts
  tests/src/logic/Piece.test.ts
  tests/src/logic/factory/PieceFactory.test.ts
  tests/src/logic/factory/pieceFactory/AdvisorFactory.test.ts
  tests/src/logic/factory/pieceFactory/PawnFactory.test.ts
  tests/src/logic/factory/pieceFactory/RookFactory.test.ts
  tests/src/logic/pieces/Advisor.test.ts
  tests/src/logic/pieces/Pawn.test.ts
  tests/src/logic/pieces/Rook.test.ts
Labels: priority.high

#29 2-logic-for-horse
  src/logic/Piece.ts
  src/logic/Position.ts
  src/logic/factory/PieceFactory.ts
  src/logic/factory/pieceFactory/AdvisorFactory.ts
  src/logic/factory/pieceFactory/HorseFactory.ts
  src/logic/factory/pieceFactory/PawnFactory.ts
  src/logic/factory/pieceFactory/RookFactory.ts
  src/logic/pieces/Advisor.ts
  src/logic/pieces/Horse.ts
  src/logic/pieces/Pawn.ts
  src/logic/pieces/Rook.ts
  tests/src/logic/Piece.test.ts
  tests/src/logic/Position.test.ts
  tests/src/logic/factory/PieceFactory.test.ts
  tests/src/logic/factory/pieceFactory/HorseFactory.test.ts
  tests/src/logic/pieces/Advisor.test.ts
  tests/src/logic/pieces/Horse.test.ts
  tests/src/logic/pieces/Pawn.test.ts
  tests/src/logic/pieces/Rook.test.ts
Labels: priority.medium

#28 fix: 0 is mistakenly taken as null value in Optional.of
  src/logic/utils/Optional.ts
Labels: type.bug, priority.medium

#27 4-logic-for-elephant
  src/logic/factory/pieceFactory/ElephantFactory.ts
  src/logic/pieces/Elephant.ts
  tests/src/logic/factory/pieceFactory/ElephantFactory.test.ts
  tests/src/logic/pieces/Elephant.test.ts
Labels: priority.medium
